# Generated by Django 3.2 on 2024-08-23 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_unique_email_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirmation_code',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.SlugField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Username may contain only letters,numbers, hyphens, and underscores.', regex='^[a-zA-Z0-9-_]+$'), django.core.validators.MaxLengthValidator(150)]),
        ),
    ]
