# Generated by Django 3.2 on 2024-08-26 08:57

from django.db import migrations, models

import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20240823_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.SlugField(max_length=150, unique=True, validators=[users.validators.validate_username, users.validators.validate_username_format]),
        ),
    ]
