# Generated by Django 3.2 on 2024-08-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.SlugField(choices=[('user', 'User'), ('admin', 'Admin'), ('moderator', 'Moderator'), ('superuser', 'Superuser')], default='user'),
        ),
    ]
