# Generated by Django 3.2 on 2024-08-18 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20240818_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_titles', to='reviews.review')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_titles', to='reviews.title')),
            ],
        ),
        migrations.AddConstraint(
            model_name='reviewtitle',
            constraint=models.UniqueConstraint(fields=('title_id', 'review_id'), name='unique_review_title'),
        ),
    ]
